// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.message;

public final class MsgBuffer {
  private MsgBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .MsgHead msghead = 1;
    /**
     * <code>required .MsgHead msghead = 1;</code>
     */
    boolean hasMsghead();
    /**
     * <code>required .MsgHead msghead = 1;</code>
     */
    com.message.MsgBuffer.MsgHead getMsghead();
    /**
     * <code>required .MsgHead msghead = 1;</code>
     */
    com.message.MsgBuffer.MsgHeadOrBuilder getMsgheadOrBuilder();

    // required bytes msgbody = 2;
    /**
     * <code>required bytes msgbody = 2;</code>
     */
    boolean hasMsgbody();
    /**
     * <code>required bytes msgbody = 2;</code>
     */
    com.google.protobuf.ByteString getMsgbody();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }

    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.message.MsgBuffer.MsgHead.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = msghead_.toBuilder();
              }
              msghead_ = input.readMessage(com.message.MsgBuffer.MsgHead.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msghead_);
                msghead_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgbody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.MsgBuffer.internal_static_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.MsgBuffer.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.message.MsgBuffer.Msg.class, com.message.MsgBuffer.Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .MsgHead msghead = 1;
    public static final int MSGHEAD_FIELD_NUMBER = 1;
    private com.message.MsgBuffer.MsgHead msghead_;
    /**
     * <code>required .MsgHead msghead = 1;</code>
     */
    public boolean hasMsghead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .MsgHead msghead = 1;</code>
     */
    public com.message.MsgBuffer.MsgHead getMsghead() {
      return msghead_;
    }
    /**
     * <code>required .MsgHead msghead = 1;</code>
     */
    public com.message.MsgBuffer.MsgHeadOrBuilder getMsgheadOrBuilder() {
      return msghead_;
    }

    // required bytes msgbody = 2;
    public static final int MSGBODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msgbody_;
    /**
     * <code>required bytes msgbody = 2;</code>
     */
    public boolean hasMsgbody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes msgbody = 2;</code>
     */
    public com.google.protobuf.ByteString getMsgbody() {
      return msgbody_;
    }

    private void initFields() {
      msghead_ = com.message.MsgBuffer.MsgHead.getDefaultInstance();
      msgbody_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsghead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgbody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMsghead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, msghead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, msgbody_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msghead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msgbody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.message.MsgBuffer.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.MsgBuffer.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.MsgBuffer.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.MsgBuffer.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.MsgBuffer.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.MsgBuffer.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.message.MsgBuffer.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.message.MsgBuffer.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.message.MsgBuffer.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.MsgBuffer.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.MsgBuffer.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.MsgBuffer.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.MsgBuffer.internal_static_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.MsgBuffer.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.message.MsgBuffer.Msg.class, com.message.MsgBuffer.Msg.Builder.class);
      }

      // Construct using com.message.MsgBuffer.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgheadFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgheadBuilder_ == null) {
          msghead_ = com.message.MsgBuffer.MsgHead.getDefaultInstance();
        } else {
          msgheadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        msgbody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.MsgBuffer.internal_static_Msg_descriptor;
      }

      public com.message.MsgBuffer.Msg getDefaultInstanceForType() {
        return com.message.MsgBuffer.Msg.getDefaultInstance();
      }

      public com.message.MsgBuffer.Msg build() {
        com.message.MsgBuffer.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.message.MsgBuffer.Msg buildPartial() {
        com.message.MsgBuffer.Msg result = new com.message.MsgBuffer.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (msgheadBuilder_ == null) {
          result.msghead_ = msghead_;
        } else {
          result.msghead_ = msgheadBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgbody_ = msgbody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.MsgBuffer.Msg) {
          return mergeFrom((com.message.MsgBuffer.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.message.MsgBuffer.Msg other) {
        if (other == com.message.MsgBuffer.Msg.getDefaultInstance()) return this;
        if (other.hasMsghead()) {
          mergeMsghead(other.getMsghead());
        }
        if (other.hasMsgbody()) {
          setMsgbody(other.getMsgbody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsghead()) {
          
          return false;
        }
        if (!hasMsgbody()) {
          
          return false;
        }
        if (!getMsghead().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.message.MsgBuffer.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.message.MsgBuffer.Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .MsgHead msghead = 1;
      private com.message.MsgBuffer.MsgHead msghead_ = com.message.MsgBuffer.MsgHead.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.message.MsgBuffer.MsgHead, com.message.MsgBuffer.MsgHead.Builder, com.message.MsgBuffer.MsgHeadOrBuilder> msgheadBuilder_;
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public boolean hasMsghead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public com.message.MsgBuffer.MsgHead getMsghead() {
        if (msgheadBuilder_ == null) {
          return msghead_;
        } else {
          return msgheadBuilder_.getMessage();
        }
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public Builder setMsghead(com.message.MsgBuffer.MsgHead value) {
        if (msgheadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msghead_ = value;
          onChanged();
        } else {
          msgheadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public Builder setMsghead(
          com.message.MsgBuffer.MsgHead.Builder builderForValue) {
        if (msgheadBuilder_ == null) {
          msghead_ = builderForValue.build();
          onChanged();
        } else {
          msgheadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public Builder mergeMsghead(com.message.MsgBuffer.MsgHead value) {
        if (msgheadBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              msghead_ != com.message.MsgBuffer.MsgHead.getDefaultInstance()) {
            msghead_ =
              com.message.MsgBuffer.MsgHead.newBuilder(msghead_).mergeFrom(value).buildPartial();
          } else {
            msghead_ = value;
          }
          onChanged();
        } else {
          msgheadBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public Builder clearMsghead() {
        if (msgheadBuilder_ == null) {
          msghead_ = com.message.MsgBuffer.MsgHead.getDefaultInstance();
          onChanged();
        } else {
          msgheadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public com.message.MsgBuffer.MsgHead.Builder getMsgheadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMsgheadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      public com.message.MsgBuffer.MsgHeadOrBuilder getMsgheadOrBuilder() {
        if (msgheadBuilder_ != null) {
          return msgheadBuilder_.getMessageOrBuilder();
        } else {
          return msghead_;
        }
      }
      /**
       * <code>required .MsgHead msghead = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.message.MsgBuffer.MsgHead, com.message.MsgBuffer.MsgHead.Builder, com.message.MsgBuffer.MsgHeadOrBuilder> 
          getMsgheadFieldBuilder() {
        if (msgheadBuilder_ == null) {
          msgheadBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.message.MsgBuffer.MsgHead, com.message.MsgBuffer.MsgHead.Builder, com.message.MsgBuffer.MsgHeadOrBuilder>(
                  msghead_,
                  getParentForChildren(),
                  isClean());
          msghead_ = null;
        }
        return msgheadBuilder_;
      }

      // required bytes msgbody = 2;
      private com.google.protobuf.ByteString msgbody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msgbody = 2;</code>
       */
      public boolean hasMsgbody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes msgbody = 2;</code>
       */
      public com.google.protobuf.ByteString getMsgbody() {
        return msgbody_;
      }
      /**
       * <code>required bytes msgbody = 2;</code>
       */
      public Builder setMsgbody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msgbody = 2;</code>
       */
      public Builder clearMsgbody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgbody_ = getDefaultInstance().getMsgbody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Msg)
    }

    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Msg)
  }

  public interface MsgHeadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 msgid = 1;
    /**
     * <code>required int32 msgid = 1;</code>
     *
     * <pre>
     *message id 0x0000 - 0xFFFF
     * </pre>
     */
    boolean hasMsgid();
    /**
     * <code>required int32 msgid = 1;</code>
     *
     * <pre>
     *message id 0x0000 - 0xFFFF
     * </pre>
     */
    int getMsgid();

    // optional string msgdate = 2;
    /**
     * <code>optional string msgdate = 2;</code>
     *
     * <pre>
     *date stamp
     * </pre>
     */
    boolean hasMsgdate();
    /**
     * <code>optional string msgdate = 2;</code>
     *
     * <pre>
     *date stamp
     * </pre>
     */
    java.lang.String getMsgdate();
    /**
     * <code>optional string msgdate = 2;</code>
     *
     * <pre>
     *date stamp
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgdateBytes();

    // required string msgmd5 = 3;
    /**
     * <code>required string msgmd5 = 3;</code>
     *
     * <pre>
     *md5(msgid,date,SecretKey)
     * </pre>
     */
    boolean hasMsgmd5();
    /**
     * <code>required string msgmd5 = 3;</code>
     *
     * <pre>
     *md5(msgid,date,SecretKey)
     * </pre>
     */
    java.lang.String getMsgmd5();
    /**
     * <code>required string msgmd5 = 3;</code>
     *
     * <pre>
     *md5(msgid,date,SecretKey)
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgmd5Bytes();
  }
  /**
   * Protobuf type {@code MsgHead}
   */
  public static final class MsgHead extends
      com.google.protobuf.GeneratedMessage
      implements MsgHeadOrBuilder {
    // Use MsgHead.newBuilder() to construct.
    private MsgHead(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgHead(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgHead defaultInstance;
    public static MsgHead getDefaultInstance() {
      return defaultInstance;
    }

    public MsgHead getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgdate_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msgmd5_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.MsgBuffer.internal_static_MsgHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.MsgBuffer.internal_static_MsgHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.message.MsgBuffer.MsgHead.class, com.message.MsgBuffer.MsgHead.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgHead> PARSER =
        new com.google.protobuf.AbstractParser<MsgHead>() {
      public MsgHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgHead(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgHead> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 msgid = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgid_;
    /**
     * <code>required int32 msgid = 1;</code>
     *
     * <pre>
     *message id 0x0000 - 0xFFFF
     * </pre>
     */
    public boolean hasMsgid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgid = 1;</code>
     *
     * <pre>
     *message id 0x0000 - 0xFFFF
     * </pre>
     */
    public int getMsgid() {
      return msgid_;
    }

    // optional string msgdate = 2;
    public static final int MSGDATE_FIELD_NUMBER = 2;
    private java.lang.Object msgdate_;
    /**
     * <code>optional string msgdate = 2;</code>
     *
     * <pre>
     *date stamp
     * </pre>
     */
    public boolean hasMsgdate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msgdate = 2;</code>
     *
     * <pre>
     *date stamp
     * </pre>
     */
    public java.lang.String getMsgdate() {
      java.lang.Object ref = msgdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgdate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgdate = 2;</code>
     *
     * <pre>
     *date stamp
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgdateBytes() {
      java.lang.Object ref = msgdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string msgmd5 = 3;
    public static final int MSGMD5_FIELD_NUMBER = 3;
    private java.lang.Object msgmd5_;
    /**
     * <code>required string msgmd5 = 3;</code>
     *
     * <pre>
     *md5(msgid,date,SecretKey)
     * </pre>
     */
    public boolean hasMsgmd5() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string msgmd5 = 3;</code>
     *
     * <pre>
     *md5(msgid,date,SecretKey)
     * </pre>
     */
    public java.lang.String getMsgmd5() {
      java.lang.Object ref = msgmd5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgmd5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgmd5 = 3;</code>
     *
     * <pre>
     *md5(msgid,date,SecretKey)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgmd5Bytes() {
      java.lang.Object ref = msgmd5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgmd5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgid_ = 0;
      msgdate_ = "";
      msgmd5_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgmd5()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgdateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgmd5Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgdateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgmd5Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.message.MsgBuffer.MsgHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.MsgBuffer.MsgHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.MsgBuffer.MsgHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.MsgBuffer.MsgHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.MsgBuffer.MsgHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.MsgBuffer.MsgHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.message.MsgBuffer.MsgHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.message.MsgBuffer.MsgHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.message.MsgBuffer.MsgHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.MsgBuffer.MsgHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.MsgBuffer.MsgHead prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MsgHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.message.MsgBuffer.MsgHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.MsgBuffer.internal_static_MsgHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.MsgBuffer.internal_static_MsgHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.message.MsgBuffer.MsgHead.class, com.message.MsgBuffer.MsgHead.Builder.class);
      }

      // Construct using com.message.MsgBuffer.MsgHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgdate_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msgmd5_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.MsgBuffer.internal_static_MsgHead_descriptor;
      }

      public com.message.MsgBuffer.MsgHead getDefaultInstanceForType() {
        return com.message.MsgBuffer.MsgHead.getDefaultInstance();
      }

      public com.message.MsgBuffer.MsgHead build() {
        com.message.MsgBuffer.MsgHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.message.MsgBuffer.MsgHead buildPartial() {
        com.message.MsgBuffer.MsgHead result = new com.message.MsgBuffer.MsgHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgid_ = msgid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgdate_ = msgdate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgmd5_ = msgmd5_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.MsgBuffer.MsgHead) {
          return mergeFrom((com.message.MsgBuffer.MsgHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.message.MsgBuffer.MsgHead other) {
        if (other == com.message.MsgBuffer.MsgHead.getDefaultInstance()) return this;
        if (other.hasMsgid()) {
          setMsgid(other.getMsgid());
        }
        if (other.hasMsgdate()) {
          bitField0_ |= 0x00000002;
          msgdate_ = other.msgdate_;
          onChanged();
        }
        if (other.hasMsgmd5()) {
          bitField0_ |= 0x00000004;
          msgmd5_ = other.msgmd5_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgid()) {
          
          return false;
        }
        if (!hasMsgmd5()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.message.MsgBuffer.MsgHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.message.MsgBuffer.MsgHead) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 msgid = 1;
      private int msgid_ ;
      /**
       * <code>required int32 msgid = 1;</code>
       *
       * <pre>
       *message id 0x0000 - 0xFFFF
       * </pre>
       */
      public boolean hasMsgid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgid = 1;</code>
       *
       * <pre>
       *message id 0x0000 - 0xFFFF
       * </pre>
       */
      public int getMsgid() {
        return msgid_;
      }
      /**
       * <code>required int32 msgid = 1;</code>
       *
       * <pre>
       *message id 0x0000 - 0xFFFF
       * </pre>
       */
      public Builder setMsgid(int value) {
        bitField0_ |= 0x00000001;
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgid = 1;</code>
       *
       * <pre>
       *message id 0x0000 - 0xFFFF
       * </pre>
       */
      public Builder clearMsgid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgid_ = 0;
        onChanged();
        return this;
      }

      // optional string msgdate = 2;
      private java.lang.Object msgdate_ = "";
      /**
       * <code>optional string msgdate = 2;</code>
       *
       * <pre>
       *date stamp
       * </pre>
       */
      public boolean hasMsgdate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msgdate = 2;</code>
       *
       * <pre>
       *date stamp
       * </pre>
       */
      public java.lang.String getMsgdate() {
        java.lang.Object ref = msgdate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgdate = 2;</code>
       *
       * <pre>
       *date stamp
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgdateBytes() {
        java.lang.Object ref = msgdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgdate = 2;</code>
       *
       * <pre>
       *date stamp
       * </pre>
       */
      public Builder setMsgdate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgdate = 2;</code>
       *
       * <pre>
       *date stamp
       * </pre>
       */
      public Builder clearMsgdate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgdate_ = getDefaultInstance().getMsgdate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgdate = 2;</code>
       *
       * <pre>
       *date stamp
       * </pre>
       */
      public Builder setMsgdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgdate_ = value;
        onChanged();
        return this;
      }

      // required string msgmd5 = 3;
      private java.lang.Object msgmd5_ = "";
      /**
       * <code>required string msgmd5 = 3;</code>
       *
       * <pre>
       *md5(msgid,date,SecretKey)
       * </pre>
       */
      public boolean hasMsgmd5() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string msgmd5 = 3;</code>
       *
       * <pre>
       *md5(msgid,date,SecretKey)
       * </pre>
       */
      public java.lang.String getMsgmd5() {
        java.lang.Object ref = msgmd5_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgmd5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgmd5 = 3;</code>
       *
       * <pre>
       *md5(msgid,date,SecretKey)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgmd5Bytes() {
        java.lang.Object ref = msgmd5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgmd5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgmd5 = 3;</code>
       *
       * <pre>
       *md5(msgid,date,SecretKey)
       * </pre>
       */
      public Builder setMsgmd5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgmd5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgmd5 = 3;</code>
       *
       * <pre>
       *md5(msgid,date,SecretKey)
       * </pre>
       */
      public Builder clearMsgmd5() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgmd5_ = getDefaultInstance().getMsgmd5();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgmd5 = 3;</code>
       *
       * <pre>
       *md5(msgid,date,SecretKey)
       * </pre>
       */
      public Builder setMsgmd5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgmd5_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgHead)
    }

    static {
      defaultInstance = new MsgHead(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MsgHead)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MsgHead_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MsgHead_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\"1\n\003Msg\022\031\n\007msghead\030\001 \002(\0132\010.Ms" +
      "gHead\022\017\n\007msgbody\030\002 \002(\014\"9\n\007MsgHead\022\r\n\005msg" +
      "id\030\001 \002(\005\022\017\n\007msgdate\030\002 \001(\t\022\016\n\006msgmd5\030\003 \002(" +
      "\tB\030\n\013com.messageB\tMsgBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_descriptor,
              new java.lang.String[] { "Msghead", "Msgbody", });
          internal_static_MsgHead_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MsgHead_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MsgHead_descriptor,
              new java.lang.String[] { "Msgid", "Msgdate", "Msgmd5", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
